name: heimdall_tools
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [windows-latest, windows-2019, windows-2016, ubuntu-latest, ubuntu-18.04, ubuntu-16.04, macOS-latest, macOS-10.14]
        ruby: [2.4]
    steps:
      - name: Checkout heimdall_tools
        uses: actions/checkout@v1
      - name: Use Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
        uses: actions/setup-ruby@v1
      - name: Run bundle install
        run: |
          bundle install
      - name: Run rake test
        run: |
          rake test
#      - name: Install rubocop
#        run: |
#          gem install rubocop
#      - name: Run rubocop
#        run: |
#          rubocop
      - name: Build heimdall_tools gem 
        run: | 
          gem build heimdall_tools.gemspec
      - name: Install heimdall_tools gem
        run: |
          gem install heimdall_tools
      - name: Run heimdall_tools
        run: |
          heimdall_tools
        env:
          CI: true
        
